### ISSUE TITLE
Syriac: Alaph on its own?

### ISSUE THREAD

**Issue by alfiedotwtf** [n8willis/opentype-shaping-documents#103]
Writing tests, and I've bumped into a possible ambiguity:

- If the preceding character's JOINING_GROUP is DALATH_RISH
   Alaph => fin2
- If the preceding character's JOINING_GROUP is not DALATH_RISH
   Alaph => fin3

What happens when Alaph is on it's own? I'm guessing that should still be ISOL. Is this correct? If so, maybe we should be explicit before the first `if`:

- if there are no preceding characters, tag the Alaph as `ISOL`

**Comment by n8willis** [comment]
I agree that that's almost certainly what should happen. I have one Syriac reader I can ping, just in case, but I expect that the change makes sense.

**Comment by n8willis** [comment]
So, before the first (general-purpose) loop, we do state this: "This computation starts from the first letter of the word, temporarily tagging the letter for `isol` substitution. If the first letter is the only letter in the word, the `isol` tag will remain unchanged."

Would it eliminate the ambiguity to simply reformat in a way making it clear that this line applies to *everything* that follows, and not just the first loop?

**Comment by n8willis** [comment]
Well, when I (finally) got around to having a conversation with someone who has genuine script experience, the answer is as expected, Alaph alone stays `isol`. Sorry that took ages. 

The consultation led to a couple of other possible changes I need to get my head around. I'll check out the PR at the same time and make sure those info streams get properly converged.

**Comment by alfiedotwtf** [comment]
I think this can be closed. You were right before, saying that you already tag `ISOL` at the start. Sorry, I completely missed that even that it was obvious by definition.
