### ISSUE TITLE
Devanagari Character marks $0956 and $0957 cannot be positioned w.r.t any base glyph

### ISSUE THREAD

**Issue by advaita56** [n8willis/opentype-shaping-documents#113]
1. Devanagari Unicode Block $0900 to $097F.
2. The characters within this block, namely $0956 and $0957, are below base mark glyphs. These should be accurately positioned w.r.t base glyphs just as the glyph $0952.
3. However whether we use the Devanagari script "dev" or the script "dev2" in our font Sanskrit2020.otf, the anchors and positioning for these glyphs $0956 and $0957 does not render in Microsoft Word 2016, 2019 or Office 365.
https://sourceforge.net/projects/advaita-sharada-font/files/Devanagari/
4. Where or what is the way to overcome this?
5. Existing commercial fonts from Adobe, Microsoft, or Indian Type Foundry do not have the Unicode characters $0956 and $0957.
[bug1 in OpenType Devanagari script.docx](https://github.com/n8willis/opentype-shaping-documents/files/5552103/bug1.in.OpenType.Devanagari.script.docx)
![bug1 in OpenType Devanagari script](https://user-images.githubusercontent.com/63571731/99364123-9b192f80-28db-11eb-9ad7-a44d6c6131b5.jpg)
[bug1 in OpenType Devanagari script.pdf](https://github.com/n8willis/opentype-shaping-documents/files/5552105/bug1.in.OpenType.Devanagari.script.pdf)

**Comment by kalapi** [comment]
Hi @advaita56, 

I was curious about the issues you've filed so I decided to look into this. Purely from an administration point of view, these issues don't belong to this repository. The OpenType Shaping Documents aim to consolidate script-shaping information for font and app developers to correctly implement shaping behaviour.

Having said that, I had a quick look at the `Sanskrit2020.otf` font file and I don't see any mark-positioning instructions for U+0956 and U+0957. This is a font issue and I recommend you speak to the developer of the font to fix this bug.

**Comment by n8willis** [comment]
HI @advaita56 

Kalapi is correct about this repository; it is just documents about how shaping is intended to be implemented in software. If you're encountering problems with a specific font, you will want to get in touch with the developers of the font itself (OAH?). 

Under the circumstances, I think I will mark these issues as closed, but they will all remain visible so you can still refer people to the URLs if that helps in tracking down the right folks for the font-engineering work.
