### ISSUE TITLE
[Devanagari] Example image missing for `init`

### ISSUE THREAD

**Issue by n8willis** [n8willis/opentype-shaping-documents#2]
https://github.com/n8willis/opentype-shaping-documents/blob/master/images/devanagari/devanagari-image-generation-log.md#5-init

**Comment by kalapi** [comment]
Yup, `INIT` isn't used in Devanagari, as there are not initial forms of consonants.

**Comment by n8willis** [comment]
Well, I guess I'm going to go ahead and close this, although I think there's some still some "upstream" things that people will have to keep in mind.

I was really hoping to find a source documenting this in the OpenType spec. Unfortunately, even as of v.1.8.2, it defines `init` as applying only to joining scripts as listed in Unicode's ArabicShaping.txt 

... and implementers just have to know from elsewhere that that description is inaccurate and that it also applies to Bengali. [ There's a least a public source on that to point to here: http://typedrawers.com/discussion/1254/final-intial-features ] 

The nagging question, in my mind, is why this feature is applied to Bengali, where sources suggest it's specifically intended for left matras, but not for other scripts that have left matras.

I'll push a change to the docs themselves that marks the feature as Bengali-only without altering the "overall order" list.

Then I'll probably close #11 as well.

**Comment by n8willis** [comment]
Closed with ee197f3.
