### ISSUE TITLE
BASE_POS_FIRST

### ISSUE THREAD

**Issue by mikeday** [n8willis/opentype-shaping-documents#31]
https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-indic-general.md#21-base-consonant

The Indic general spec still references BASE_POS_FIRST, but no Indic scripts use this?

**Comment by n8willis** [comment]
Well, BASE_POS_FIRST is used in Khmer and Myanmar -- which, for ease of implementation, share most of the same terminology as the scripts in the Indic shaper doc.  HarfBuzz, at least, used to include Khmer in the Indic shaper, although I think it proved to be more trouble than it was worth, considering all the exceptions.

That's probably the origin of it in the HarfBuzz model, though. I would be in favor of keeping the terminology around; there may still be other scripts from the Indic region not on the current list that it applies to, and I think that keeping parallels to the Indic model helps standalone scripts like Khmer and Myanmar be more easily understood. Possibly USE as well.

Perhaps adding a note here to that effect would be the right move?

**Comment by mikeday** [comment]
Yes, adding a note would clarify that it's intentional.

**Comment by n8willis** [comment]
Note added in 06c902c and d3016e9 — also noted REPH_MODE_VISUAL_REPHA.
