### ISSUE TITLE
Tag decomposed matras

### ISSUE THREAD

**Issue by mikeday** [n8willis/opentype-shaping-documents#33]
https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-indic-general.md#23-tag-decomposed-matras

"All single-part matras can be tagged based on their Mark-positioning subclass."

Given that the mark placement subclass is left/right/top/bottom, how does one determine the appropriate sorting tag from this? (eg. POS_PREBASE_MATRA).

**Comment by n8willis** [comment]
The mark-positioning subclasses use left|right|top|bottom (or combinations), which map to pre|post|above|below -- for everybody.

Then, in each script's "shaping characteristics" there are sort-order positions for each of those. But those may not be simple.... For instance, all the Indic scripts say that left/pre matras get sorted into the POS_PREBASE_MATRA position. But Kannada has some right/post matras that get sorted into one position and some that get sorted into another: https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-kannada.md#the-knd2-shaping-model

I take it that we should be more explicit about this? Perhaps a table in the "shaping characteristics" subsection?

**Comment by n8willis** [comment]
I added an expanded note in 905c09d that hopefully clarifies.

**Comment by n8willis** [comment]
Good point; it is just Kannada and Telugu AFAICT. Added note in 86eb4d4.
