### ISSUE TITLE
Tagging Bengali post-base consonants

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#38]
Hi @n8willis,

I've got a couple of questions about post-base consonant tagging:

1. [Section 2.7](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-bengali.md#27-post-base-consonants) in the Bengali spec mentions that any non-base consonants that occur after a matra should be tagged with `POS_POSTBASE_CONSONANT`. HarfBuzz appears to tag them with (their version of) `POS_FINAL_CONSONANT` instead, plus there is a comment mentioning that this only occurs in Sinhala. Highlighted HarfBuzz code [here](https://github.com/harfbuzz/harfbuzz/blob/5cd544a621f10b307bb97aea27ea54e55aacb2e9/src/hb-ot-shape-complex-indic.cc#L653-L663). Are we taking a different approach here? (The syllables we scraped from Wikipedia contain a fair number of "Ya", "Ba" and "Ra" consonants that occur after the base consonant but do not occur after a matra, thus leaving them untagged).

2. The same section mentions that Bengali "includes one post-base consonant" ("Ya"), but [Section 1](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-bengali.md#1-identifying-syllables-and-other-sequences) contradicts that by saying "three consonants in Bengali are allowed to occur in post-base position: "Ya", "Ba", and "Ra"." Is the statement in Section 1 the correct one? These same scraped syllables imply that it is.

**Comment by n8willis** [comment]
(in reverse order....)

2. Section one is correct; that's just a bug for me.

1. For POS_FINAL_ vs POS_POSTBASE_, are you looking at the output of hb_shape, or just at the source code?

**Comment by adrianwong** [comment]
> For POS_FINAL_ vs POS_POSTBASE_, are you looking at the output of hb_shape, or just at the source code?

Just at the source code!

**Comment by n8willis** [comment]
(2). The fix here is for me to update the discussion text, saying that 'three consonants can occur after the base consonant: the post-base Ya and the the two below-base, Ra and Ba.

Item (1) is, I think, subsumed by the corrections on #41.

**Comment by n8willis** [comment]
Pushed 9ef09bb, propagating the revised language from Bengali to all non-SInhala Indic scripts. I think this is covered in the update, but as on the other two issues, have a look and let me know how it reads before I close it.

**Comment by adrianwong** [comment]
Looks good!
