### ISSUE TITLE
Base consonant algorithm

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#40]
### Bengali Ya-Phalaa

Consider the Bengali "Ra, ZWJ, Halant, Ya" sequence, where the ZWJ is inserted immediately after the "Ra" to obtain the _ya-phalaa_ ([Unicode 11, page 472](https://www.unicode.org/versions/Unicode11.0.0/ch12.pdf)).

Based on our spec, we exclude "Ra" from being considered for the base consonant and make "Ya" our base, which is incorrect as "Ra" should be the base, with "Ya" taking on post-base form.

Should we instead modify the first step of our [algorithm](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-bengali.md#21-base-consonant) so it says:

> If the syllable starts with **a "Ra, Halant" sequence** and the syllable contains more than one consonant, exclude the starting "Ra" from the list of consonants to be considered.

### Half Forms

Consider the Bengali "Ka, Halant, ZWJ, Ya" sequence. We skip "Ya" because it has a post-base form and make "Ka" the base consonant, even though the sequence "Ka, Halant, ZWJ" produces a half-form.

The algorithm should contain another condition where we terminate the base consonant search on coming across a "Halant, ZWJ" sequence.

**Comment by n8willis** [comment]
On the Ra,YaPhalaa case, I don't think that change to the base-finding algorithm would fix it.... the resulting sequence would not start with "Ra, Halant", but instead with "Ra, ZWJ, Halant". Perhaps I need to examine the regular expressions for syllable identification in HarfBuzz again; make sure it's breaking syllables where expected on ZW[N}Js....

**Comment by adrianwong** [comment]
Hmmm! I think it may not break for ZWJs in this position unfortunately. In HarfBuzz:

```
consonant_syllable = (Repha|CS)? cn complex_syllable_tail;

where:

cn = c.ZWJ?.n?;
c = (C | Ra);
complex_syllable_tail = (halant_group.cn){0,4} halant_or_matra_group syllable_tail;
halant_group = (z?.H.(ZWJ.N?)?);
```

`cn` : `c.ZWJ` : "Ra" + "ZWJ"
`(halant_group.cn){1}` : `H.cn` : `H.C` : "Halant" + "Ya"
