### ISSUE TITLE
"Consonant, Matra, Halant"

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#42]
Our state machine recognises a `Consonant, Matra, Halant` sequence as a valid consonant syllable.

Please forgive my ignorance here, but how should this sequence be interpreted?

- The `Consonant` in this sequence is the base consonant, as it is the only consonant in the sequence.
- The base consonant carries the syllable's vowel sound, which is provided by the `Matra` and not the base consonant's inherent vowel.
- A `Halant` is meant to strip a consonant of its inherent vowel, but here it is placed after the `Matra`. What is the significance of the `Halant`?

**Comment by n8willis** [comment]
Can you show me where you've run into this? Meaning, is there example text?

Alternatively, is it just falling out of the regular expressions?

**Comment by n8willis** [comment]
Thanks @dscorbett.
