### ISSUE TITLE
BLWF substitutions in Indic scripts with BLWF_MODE_PRE_AND_POST

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#44]
For Indic scripts that have the `BLWF_MODE_PRE_AND_POST` characteristic, HarfBuzz [doesn't apply](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape-complex-indic.cc#L830-L832) `BLWF` substitutions to pre-base consonants under the old shaping model, but [our spec](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-bengali.md#37-blwf) does not mention such a restriction.

**Comment by n8willis** [comment]
(Untangling & pushing some commits done while hopping between machines...) 
Addressed in 78f0fa9 -- feedback welcome. May be hard to test old-spec stuff, but it is at least recorded.

**Comment by n8willis** [comment]
Pushed 9ef09bb, propagating the revised language from Bengali to all non-SInhala Indic scripts. I believe this should take care of this issue as well as the related ones mentioned above. Do take a peek and let me know how it reads, however, before I close it.

(I think this was taken care of in 78f0fa9 anyway, but it's worth a look).

**Comment by adrianwong** [comment]
Nice. I like how there's a reference to the `BLWF_MODE` in section 2.5, and the "distinctions from" section mentions that the Indic1 models are effectively `POST_ONLY`.
