### ISSUE TITLE
Shaping Indic non-consonant syllables

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#45]
I don't believe the spec covers how to shape vowel/standalone/broken/symbol syllables.

What HarfBuzz [appears to do](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape-complex-indic.hh#L72-L75) is to:

- treat independent vowels, placeholders, and dotted circles as consonants, and
- insert a dotted circle after a possible `reph` in a broken syllable so it can be [treated like a standalone syllable](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape-complex-indic.cc#L952).

This allows HarfBuzz to run the consonant syllable shaping logic on vowel, standalone, and broken syllables. (There is some additional logic with the initial reordering of standalone clusters to conform to Uniscribe behaviour).

For symbol syllables, they appear to skip the initial reordering step but not subsequent ones...? Not sure about this one.

**Comment by n8willis** [comment]
Correct about the IVs/placeholders/circles in HarfBuzz. That is certainly an optimization, though, not so much behavior to specify.

The intent in the spec was to have the "if there is one" language in the base-consonant–locating step (2.1) result in that step being a NOP for such consonantless syllables, so that implementations would just keep chugging through to steps 2.2 and onward. [E.g., this paragraph: "Vowel-based syllables, standalone sequences, and broken text runs will not have base consonants."]

Is that the thing that's not clear? Or is it somewhere else?

Early on, we had decided to try and not force too many of HarfBuzz's optimizations into the spec so as to avoid confusion. This was one of those cases. Telling people that they need to treat IVs as consonants seemed like a recipe to get developers mixed up.

**Comment by adrianwong** [comment]
What I wonder is if this step is not so much an optimisation as it may be a required part of Indic shaping.

If we disregard step 2.1, there other tagging steps that are reliant on having a "base consonant". Step 2.8 comes to mind - without a base consonant, are all consonants in an vowel-based syllable "pre-base", or "post-base"?

(From our regex, consonants can still exist in vowel-based and standalone syllables).

More fundamentally, what should the IV/circle be tagged as for initial reordering purposes?

**Comment by n8willis** [comment]
Well, it reduces code duplication anyway.

Okay, so there are actually two distinct issues here. One is wording in the spec, the other is tagging/treating the IV|circle|etc.

Fairly certain that there are no "pre-base" consonants in a vowel-based syllable.  I believe it's possible as in the yaphalaa case to have a post-base consonant (in real words; the regexp certain matches it).

From a spec-wording standpoint, we have a couple of options:
 -  Define an IV/circle as a "base" (but not a "base consonant") or "surrogate base"/"implied base"/etc, before the beginning of stage two.
 -  Explain that the consonant-based syllable is the most common case and that handling IVs/circles AS IF they were consonants reduces complexity.
 -  Write separate steps for vowel-based syllables (certainly not the ideal approach....)
 -  Add [Note] sections to the steps where base consonants are referred to after stage 2 step 1.

The first of those is probably the smallest change. I would reiterate the earlier concern that we'd be specifying 'OpenType shaping works the HarfBuzz way' though.... But whether or not that's a dealbreaker is not up to me. Or, it shouldn't be; it's something implementors should weigh in on.

The downside to approach one is that there's a whole bunch of Unicode and OpenType docs out there that talk about base consonants and IVs in a particular way.

**Comment by n8willis** [comment]
Right. It's pretty likely that Uniscribe is doing something similar, though.

No mention of this in the actual OT spec. The equivalent MS docs on shaping don't really address it either (I think this is the closest point where it would appear if it was there: https://docs.microsoft.com/en-us/typography/script-development/bengali#reorder-characters ).

**Comment by n8willis** [comment]
Revisiting this, I don't see that we have a real alternative to treating IVs and Dotted_Circles like pseudo-bases. Without that, we'd have to duplicate virtually every subsequent stage.

If the concern is chiefly one of losing Unicode's discussion about IVs, then maybe we fix that by inserting a section (early on) that discusses the issue and suggests that implementations keep track of whether a syllable starts with an IV if that is important for other purposes. At least IV-based syllables aren't going to be as complex or as common.

As for DCs, I think the case is stronger there for making a note of the problem and not overspecifying what anyone should do. That's essentially getting into handling of bad input data, and is as much UX as it is shaping. Red kryptonite.

**Comment by adrianwong** [comment]
> Red kryptonite.

😆

**Comment by n8willis** [comment]
Another issue is that if we change the base-consonant search algorithm to that it is where the post-base consonants get tagged, then these non-consonant syllables will need to go through the algorithm anyway in order to make sure that the post-base Cs get tagged.

**Comment by n8willis** [comment]
9ef09bb also includes a note about vowel-based syllables in 2.1. If necessary, we can elevate that (i.e., 'pseudo-bases') to make it more prominent, but first it needs a read-through in context I think.

**Comment by adrianwong** [comment]
My opinion is that it's fine where it is in section 2.1.

One point for discussion regarding this change. Earlier on in the thread you mentioned:

> Fairly certain that there are no "pre-base" consonants in a vowel-based syllable. I believe it's possible as in the yaphalaa case to have a post-base consonant (in real words; the regexp certain matches it).

I know this now, but someone unfamiliar with the literature may get a little confused when reading:

> Because vowel-based syllables will not include consonants

Could we replace "consonants" with something like "base-qualifying consonants"? Or will that serve to confuse the reader further?

**Comment by n8willis** [comment]
> Could we replace "consonants" with something like "base-qualifying consonants"? Or will that serve to confuse the reader further?

I agree that we need an update. I'm not 100% sure what it ought to say, though. As I understand it, Yaphala is allowable because it modifies the vowel sound; I am not sure how many other post-base forms fall under that umbrella, or if that also ought to include any below-base forms, final consonants in Sinhala, etc. Checking around now.

**Comment by lianghai** [comment]
The historical differentiation of “independent vowel letters vs consonant letters” is premature. Experts’ understanding is moving towards recognizing both independent vowel letters and consonant letters as just base letters, in terms of encoding and shaping.

The Unicode Core Spec’s Indic chapters are kinda stuck in earlier understandings and just beg for an overhaul (I’ll get to it). Don’t take the Core Spec’s phrasing and analysis model too serious when you guys apparently know what you’re doing.

**Comment by n8willis** [comment]
@lianghai Any guidance as to whether or not we ought to expect pre-base and post-base consonant forms in a syllable that starts with an independent vowel?

It seems like if that doesn't happen, it simplifies life from the shaping-algorithm perspective.

**Comment by n8willis** [comment]
I've been putting together a branch that tries to explain/handle the IV-based syllable case more correctly (and deal with artificial bases like dotted circles) in a coherent manner....

@adrianwong have you got examples in the Wikipedia corpus of matras or special-form consonants on IV-based syllables?

**Comment by adrianwong** [comment]
Sure thing. Here are some examples with অ (U+0985 Bengali Letter A):

* অ্যা - post-base C2-conjoining form; right matra. [Sample Wikipedia page](https://bn.wikipedia.org/wiki/%E0%A6%85%E0%A7%8D%E0%A6%AF%E0%A6%BE_%E0%A6%B8%E0%A7%8B%E0%A6%B8%E0%A6%BE%E0%A6%B0%E0%A6%AB%E0%A7%81%E0%A6%B2_%E0%A6%85%E0%A6%AC_%E0%A6%B8%E0%A6%BF%E0%A6%95%E0%A7%8D%E0%A6%B0%E0%A7%87%E0%A6%9F%E0%A7%8D%E2%80%8C%E0%A6%B8).
* অ্র্য - below-base + post-base C2-conjoining form. Its only usage in the corpus appears to be in the phrase "হার্ট অ্র্যাটাক"
* অ্যাি, অ্যাো - left matras
* অ্যু - bottom matra
* অঁ - candrabindu

Will these suffice, or would you like me to send through more examples via email?

**Comment by n8willis** [comment]
No, that's great. Thanks! 

In reassessing this change, I'm considering the possibility that it would simplify things a lot to replace `BASE_CONSONANT` with `BASE_LETTER` in the sort positions. Or maybe `SYLLABLE_BASE` or something like that. In the current text, there are a lot of spots that require updating to address IV-bases. 

Can't lose the distinction entirely, I think, since that would confuse the "BASE_POS_*" concept. But by altering the sort orders to be a little broader, there's less patching to do — although there are still spots where discussion is necessary of course.

**Comment by n8willis** [comment]
Okay. I placed an in-progress revision in #83 — but only for Devanagari. It was more helpful to implement changes on a full script doc than to try and do it in Indic General. Comments are welcome.

**Comment by n8willis** [comment]
Closing this, since the PR has been merged and did not seem to spawn further issues.
