### ISSUE TITLE
Pre-base-reordering "Ra" in Telugu

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#55]
As part of lengthier discussions in #32 and #41, it's been mentioned that (for Indic scripts at least) pre-base-reordering "Ra" only exists in Malayalam.

However, the Nirmala font has encoded it for Telugu too, and [this](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-39pref39) OpenType entry mentions that Telugu "may display a pre-base form of "Ra"".

E.g. "Ga, Halant, Ra" using Nirmala:
![Screen Shot 2019-03-19 at 10 47 02 am](https://user-images.githubusercontent.com/8623831/54570895-7993e080-4a34-11e9-8648-376fea9e377d.png)

**Comment by n8willis** [comment]
OK; will update. I don't have a Windows box with which to test, but I definitely trust Tiro on such matters.

**Comment by n8willis** [comment]
Fixed by 8636ebf.
