### ISSUE TITLE
[Indic] Position of multi-part matras without canonical Unicode decomposition

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#62]
As far as I'm aware, there are two multi-part matras without a canonical Unicode decomposition. Gujarati's "Candra O" (U+0AC9) and Oriya's "Au Length Mark" (U+0B57).

For purposes of initial reordering, what should their position tags be, assuming these matras remain composed?

Both vowels are comprised of one above-base and one right-side mark, is it "correct" to assume that their positions are `POS_AFTER_POST`, given that the above-base mark moves along with the right-side mark?

**Comment by lianghai** [comment]
U+0AC9 GUJARATI VOWEL SIGN CANDRA O and U+0B57 ORIYA AU LENGTH MARK are not typical “multi-part” vowel signs. Instead, they behave more like U+094B ो DEVANAGARI VOWEL SIGN O. U+0AC9 and U+0B57 have `Indic_Positional_Category = Top_And_Right` mostly only because InPC is not yet clearly defined.

Note that “को કૉ କୗ” are not expected to look like “केा કૅા କୖା”.

**Comment by behdad** [comment]
My answer is "whatever HarfBuzz does".  Checking the code, looks like we just accept what comes in from Unicode tables for those, assuming the mapping:
```
  /* These should resolve to the position of the last part of the split sequence. */
  INDIC_MATRA_CATEGORY_BOTTOM_AND_RIGHT                 = INDIC_MATRA_CATEGORY_RIGHT,
  INDIC_MATRA_CATEGORY_LEFT_AND_RIGHT                   = INDIC_MATRA_CATEGORY_RIGHT,
  INDIC_MATRA_CATEGORY_TOP_AND_BOTTOM                   = INDIC_MATRA_CATEGORY_BOTTOM,
  INDIC_MATRA_CATEGORY_TOP_AND_BOTTOM_AND_RIGHT         = INDIC_MATRA_CATEGORY_RIGHT,
  INDIC_MATRA_CATEGORY_TOP_AND_LEFT                     = INDIC_MATRA_CATEGORY_TOP,
  INDIC_MATRA_CATEGORY_TOP_AND_LEFT_AND_RIGHT           = INDIC_MATRA_CATEGORY_RIGHT,
  INDIC_MATRA_CATEGORY_TOP_AND_RIGHT                    = INDIC_MATRA_CATEGORY_RIGHT,
```

**Comment by n8willis** [comment]
Updated the notes in section 2.2 for both Gujarati and Oriya in 22fcabd.
