### ISSUE TITLE
[Indic] Pre-base matra, Halant position tagging

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#63]
During the initial reorder, [mark tagging](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-indic-general.md#28-mark-tagging) process, Uniscribe and [HarfBuzz](https://github.com/harfbuzz/harfbuzz/blob/c96c6b287ff1d96da6a50a8cb3f641fe8705e5f7/src/hb-ot-shape-complex-indic.cc#L735-L743) do not tag a Halant with the same positioning tag as the preceding character, if that character is a pre-base matra.

Two examples illustrating this:

1. `U+092B (Pha), U+093F (Vowel Sign I), U+094D (Halant)`
2. `U+092B (Pha), U+0940 (Vowel Sign Ii), U+094D (Halant)`

In the first case, the Halant is positioned under the base consonant; in the second it is positioned under the matra.

**Comment by n8willis** [comment]
Should be fixed in e2b5630. Have a look when you can, and if all is well this can be closed.

**Comment by adrianwong** [comment]
Nice to have this made explicit in the spec! Happy for this to be closed.

(As an aside, I've edited the issue description - a copy/paste error meant that I had the code point of Vowel Sign Ii as U+093F, which is incorrect.)
