### ISSUE TITLE
[Indic] Devanagari exception to Indic1 BLWF_MODE_POST_ONLY

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#65]
Following on from #44, it looks like non-initial "Ra, Halant" pre-base sequences in Indic1 Devanagari is the exception to the Indic1 `BLWF_MODE_POST_ONLY` rule, at least according to [HarfBuzz](https://github.com/harfbuzz/harfbuzz/blob/c96c6b287ff1d96da6a50a8cb3f641fe8705e5f7/src/hb-ot-shape-complex-indic.cc#L854-L871).

**Comment by n8willis** [comment]
Fixed with #83
