### ISSUE TITLE
[Indic] Remove Gurmukhi Yakash (and CONSONANT_MEDIAL) from spec?

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#67]
Our Gurmukhi spec mentions the "Yakash" consonant, which Uniscribe apparently doesn't treat specially, and HarfBuzz relatively recently [removed support](https://github.com/harfbuzz/harfbuzz/commit/8bf4027d23318c7e1ff7fe9f5e7ad8b0380e5415) for.

Should we follow suit?

If we'd like to leave it in, should we explicitly specify what its position tag should be? Considering it is positioned in a "mark-like, below-base form", should we have it tagged as `POS_BELOWBASE_CONSONANT`?

**Comment by behdad** [comment]
Wait on this one. We are going to revert my change.

**Comment by behdad** [comment]
Yeah that was reverted.  See: https://github.com/harfbuzz/harfbuzz/issues/1592

**Comment by adrianwong** [comment]
Thanks @behdad. Interesting that Uniscribe and CoreText don't form a dotted circle if a "Yakash" comes after a matra. I wonder if they categorise "Yakash" as a matra, or if their regex permits consonant medials to occur after a matra group.

Considering the [L2/06-037](https://www.unicode.org/L2/L2006/06037-yakash.pdf) proposal states that the "Yakash" should be treated as a subjoined form of "Ya", it seems sensible to me that it should be tagged as `POS_BELOWBASE_CONSONANT`, but I'll defer to @n8willis on this.

**Comment by behdad** [comment]
@dscorbett

**Comment by lianghai** [comment]
`POS_BELOWBASE_CONSONANT` feels okay.

The Unicode Core Spec already states “[t]his character should occur after the consonant to which it attaches and before any vowel sign”, and I feel it’s unlikely this character will ever get a different recommended position in the encoded cluster.

**Comment by adrianwong** [comment]
Thanks @lianghai! Good to have some confirmation on this matter.

**Comment by n8willis** [comment]
Updated to specify `POS_BELOWBASE_CONSONANT` in c5364de.
