### ISSUE TITLE
[Indic] PSTF semantics

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#71]
Per the newly revised spec, we identify and tag post-base consonants with `POS_POSTBASE_CONSONANT` during the base consonant search. At a later stage, we mark these post-base consonants (and their preceding Halants) for `PSTF` feature substitution (via the use of a `PSTF` mask).

HarfBuzz on the other hand applies the `PSTF` mask to all post-base glyphs. I assume this is done for efficiency and simplicity (and there's nothing wrong with that).

However, this difference in approach has caused a number of issues when testing against our Gurmukhi corpus using Microsoft's Nirmala UI font. I'll list two examples here:

(Images from left to right: Prince, HarfBuzz, Uniscribe.)

1. ਅਂੰ - U+0A05 (Letter A), U+0A02 (Sign Bindi), U+0A70 (Tippi)

![prince1](https://user-images.githubusercontent.com/8623831/58471834-2a7ed000-8188-11e9-99f7-859a676fee77.png) ![harfbuzz1](https://user-images.githubusercontent.com/8623831/58471838-2c489380-8188-11e9-8a86-ce0d4524c483.png) ![uniscribe1](https://user-images.githubusercontent.com/8623831/58471848-310d4780-8188-11e9-87f0-f90191bf8f04.PNG)

2. ਅੇੱ - U+0A05 (Letter A), U+0A47 (Vowel Sign Ee), U+0A71 (Addak)

![prince2](https://user-images.githubusercontent.com/8623831/58471908-58641480-8188-11e9-9a0e-968f77f2e452.png) ![harfbuzz2](https://user-images.githubusercontent.com/8623831/58471913-5a2dd800-8188-11e9-8751-cdf119187ae0.png) ![uniscribe2](https://user-images.githubusercontent.com/8623831/58471918-5dc15f00-8188-11e9-8007-6b34308fa972.PNG)

In both cases, because HarfBuzz has the `PSTF` mask applied to the latter two glyphs, the Tippi and the Addak both undergo a single substitution (via a chaining contextual `PSTF` lookup).

All this was a very long-winded build-up to my actual question:

Is a `PSTF` substitution on a Bindu or Gemination Mark semantically permissible? I.e. is this a font issue, or is this something we have to cater for in the spec?

**Comment by lianghai** [comment]
> In both cases, because HarfBuzz has the `PSTF` mask applied to the latter two glyphs, the Tippi and the Addak both undergo a single substitution (via a chaining contextual `PSTF` lookup).

Would you mind providing some clarification about the `PSTF` feature/lookup (does it refer to the `pstf` feature and lookups registered to the feature?) and HarfBuzz’s `PSTF` mask?

Semantically/orthographically speaking, _bindi_ and _tippi_ are not expected to coexist on a written syllable (also they mostly have a complimentary distribution on different types of syllables), and the vowel sign _ee_ is not expected to appear on the letter _a_/_aira_ because a letter _ee_ (U+0A0F) would be used. It’s a different story whether a shaping engine should restrict such usage though.

**Comment by adrianwong** [comment]
> Would you mind providing some clarification about the PSTF feature/lookup (does it refer to the pstf feature and lookups registered to the feature?) and HarfBuzz’s PSTF mask?

If I understand your question correctly, it's referring to both - the Nirmala font appears to have PSTF feature lookups for "Bindi, Tippi" and "Vowel Sign Ee, Addak", which we don't apply because our masking strategy differs from HarfBuzz's.

> Semantically/orthographically speaking, bindi and tippi are not expected to coexist on a written syllable (also they mostly have a complimentary distribution on different types of syllables), and the vowel sign ee is not expected to appear on the letter a/aira because a letter ee (U+0A0F) would be used. It’s a different story whether a shaping engine should restrict such usage though.

Interesting, thanks heaps for clarifying that! The two examples in the original post are from Wikipedia (and probably one Gurmukhi news site), so they're out there "in the wild".

I suppose what I can take away from this exchange is that:

1. shaping engines may not restrict certain unexpected/invalid combinations, and
2. certain fonts may (erroneously or otherwise) provide lookups for said combinations.

**Comment by n8willis** [comment]
Irrespective of whether bindu-to-tippi `PSTF` substitutions mean something, the general mark-to-mark or matra-to-mark case seems like it's worth providing cover for. I'll add something to step 2.8.

**Comment by n8willis** [comment]
I added a stab at this in #89 . For it to make sense, we also have to note that tagging glyphs for potential GSUB application is a useful strategy. That seems to fit best in the intro to stage 2 (2.0?). it may also be necessary to add similar notes to the other stage 2 steps.

**Comment by n8willis** [comment]
On an unrelated note, I think I have finally decided that "sort the syllable" (which is currently a bit of an afterthought in the tail end of 2.8) needs to be promoted to a .y step in its own right, lest somebody new to the docs miss it along the way....

**Comment by adrianwong** [comment]
> On an unrelated note, I think I have finally decided that "sort the syllable" (which is currently a bit of an afterthought in the tail end of 2.8) needs to be promoted to a .y step in its own right, lest somebody new to the docs miss it along the way....

This would be nice. It'll also allow us to reference an explicit section from the code.

**Comment by n8willis** [comment]
For the record - 2.9 is made the explicit syllable-sortin' step by #93 . I probably should've opened an issue for it, but what's done is done.

**Comment by n8willis** [comment]
As for `pstf` tagging itself, I've now played around with various phrasing patches w.r.t. the GSUB-feature-masking notes, like seen in #89 ....

I'm convinced that 
  - it doesn't make sense for the docs to give equal weight to the "feature mask as you go" approach (used by HarfBuzz and Prince IIRC) AND to some hypothetical other approach that we don't have evidence for. If every non-ancient shaping engine tags for features while stepping through the initial-reordering stage, then it's better to make that official. If someone knows for a fact that some other shaping engine does employ a different approach, it'd be great to hear about it.
  - Putting feature-masking into the docs explicitly will simplify the reporting of certain issues.
  - We're already sort of halfway-referencing this approach by re-using HarfBuzz's `BLWF_MODE_*` semantics, which makes that characteristic sort of stick out, currently.

It wouldn't be a big change to just say "tag for potential feature application" during the existing 2.x steps. Are there any objections to that? Corner cases I haven't thought about?

**Comment by adrianwong** [comment]
No objections from me. I think it's great to have in the spec, if only for the ease of reporting issues. But perhaps there are things that I've failed to consider myself...

Both HarfBuzz (IIRC) and Prince apply the masks at the end of the 2.x steps. You can see what Prince has done [here](https://github.com/yeslogic/allsorts/blob/d5525fb0d1defcb981e04fdfab2e3c1bdc4a2499/src/indic.rs#L1654-L1748) - the code is heavily annotated for my future self; perhaps that may be of use to you.

**Comment by n8willis** [comment]
Definitely; please pass along my thanks to future you.

I could use a "I've been inside too long and my thinking is cloudy" check on one thing, though. You're only masking for initial GSUB (ie, stage-3) features, right? Because the stage-5 GSUB gets applied all in one pass?

Just wanting to make sure I have the logic correct in my head. In some local-branch work, I started thinking about how we'd want to discuss the comparable masking/tagging issues in Arabic shaping (or anywhere that has some default and some optional features).

So I have to convince myself that `pref` needs mentioning with respect to this, but `pres` doesn't. So if I have that right (about the difference between the stages), let me know and I'll chill out.

**Comment by adrianwong** [comment]
> I could use a "I've been inside too long and my thinking is cloudy" check on one thing, though. You're only masking for initial GSUB (ie, stage-3) features, right? Because the stage-5 GSUB gets applied all in one pass?

Yes, that is mostly correct - we do [mask](https://github.com/yeslogic/allsorts/blob/d5525fb0d1defcb981e04fdfab2e3c1bdc4a2499/src/indic.rs#L2313-L2353) the stage-5 `init` feature right before applying the single pass.

> Just wanting to make sure I have the logic correct in my head. In some local-branch work, I started thinking about how we'd want to discuss the comparable masking/tagging issues in Arabic shaping (or anywhere that has some default and some optional features).

Nice!
