### ISSUE TITLE
[Indic] Unnecessary tagging of composite Kannada matras

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#75]
[This section](https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-kannada.md#23-tag-matras) of the Kannada specification mentions that the matras:

* `U+0CC7 - Sign Ee`
* `U+0CC8 - Sign Ai`
* `U+0CCA - Sign O`
* `U+0CCB - Sign Oo`

should be given a position tag. However, these are composite matras, and would have already been decomposed in the prior step.

**Comment by n8willis** [comment]
I think that I included all the matras in that list in the step out of the "repeat information to avoid ambiguity" principle. Essentially, whenever we were enumerating matras, I wanted to ensure that they were all accounted for, in case someone arrives at the step via some unpredictable path (like a full-text search result).

So I think just clarifying that via a reword would be the best fix: note the composite issue, but don't just cut them out without explanation.

**Comment by n8willis** [comment]
Clarifying note added in d9d31cb.
