### ISSUE TITLE
[Indic] Expected merge behaviour of glyph properties

### ISSUE THREAD

**Issue by adrianwong** [n8willis/opentype-shaping-documents#77]
We've recently done a comparison of HarfBuzz and our shaping engine with regards to how each handles the merging of glyph properties during ligation. Both approaches are somewhat different, and we figured it was worth raising an issue in order to document and discuss these differences.

### HarfBuzz

(Note: As I'm relatively unfamiliar with navigating the deeper parts of the HarfBuzz code, I've instead relied on empirical analysis (i.e. `printf`s) in order to determine this behaviour.)

In a nutshell, for a forward lookup that leads to the ligation of two or more glyphs, it appears that the _leftmost_ glyph's properties is retained.

Consider the Devanagari "Ka, Halant, Ssa" sequence, which typically forms the "KSsa" ligature:

```
before ligation:
    Ka - pos: prebase, masks: half|blwf
Halant - pos: prebase, masks: half|blwf
   Ssa - pos:    base, masks: none

after ligation:
  KSsa - pos: prebase, masks: half|blwf
```

In this example, "KSsa"'s `pos` is tagged as prebase, when in principle it should be the new base consonant.

Now, for a "Ka, Halant, Ssa, Halant" sequence:

```
before ligation:
    Ka - pos: prebase, masks: half|blwf
Halant - pos: prebase, masks: half|blwf
   Ssa - pos:    base, masks: none
Halant - pos:    base, masks: blwf

after ligation:
  KSsa - pos: prebase, masks: half|blwf
Halant - pos:    base, masks: blwf
```

Of interest here is that certain fonts allow a further ligation of "KSsa, Halant" into a "KSsa" half form, and further testing shows that HarfBuzz prohibits this because the "Halant" isn't also masked with `half`. The behaviour for this particular example is in-line with Uniscribe and CoreText.

### Prince

For a forward lookup that leads to the ligation of two or more glyphs, the glyph's properties with the higher _position precedence_ is retained. Assuming all glyphs have a valid position tag, the precedence is specified as:

```
pos: base > prebase/postbase > everything else (just use leftmost glyph's properties)
```

Devanagari "Ka, Halant, Ssa":

```
before ligation:
    Ka - pos: prebase, masks: half|blwf
Halant - pos: prebase, masks: half|blwf
   Ssa - pos:    base, masks: none

after ligation:
  KSsa - pos:    base, masks: none
```

Devanagari "Ka, Halant, Ssa, Halant":

```
before ligation:
    Ka - pos: prebase, masks: half|blwf
Halant - pos: prebase, masks: half|blwf
   Ssa - pos:    base, masks: none
Halant - pos:    base, masks: none

after ligation:
  KSsa - pos:    base, masks: none
Halant - pos:    base, masks: none
```
 
By specifying this merge behaviour, this allows us to "get away with" just checking that the first glyph in a lookup has the appropriate mask applied (e.g. "Halant `[blwf]`, Ba `[]`" will suffice for the BLWF feature to apply.

Our corpus test output tracks HarfBuzz's very closely, so this approach appears to work well for Indic text at least. However, there is no saying that this approach won't fall short on non-Indic scripts.

The difference in merge behaviour causes some interesting differences:

### HarfBuzz

Noto Sans Devanagari "Ra, Halant, Ra, Halant, Ra, Halant":

```
before ligation:
       Ra [i:  52] - pos:    reph, masks: rphf|half|blwf
   Halant [i:  81] - pos:    reph, masks: rphf|half|blwf
       Ra [i:  52] - pos: prebase, masks: half|blwf
   Halant [i:  81] - pos: prebase, masks: half|blwf
       Ra [i:  52] - pos:    base, masks: none
   Halant [i:  81] - pos:    base, masks: blwf

after RPHF:
     Reph [i: 181] - pos:    reph, masks: rphf|half|blwf
       Ra [i:  52] - pos: prebase, masks: half|blwf
   Halant [i:  81] - pos: prebase, masks: half|blwf
       Ra [i:  52] - pos:    base, masks: none
   Halant [i:  81] - pos:    base, masks: blwf

after RKRF:
     Reph [i: 181] - pos:    reph, masks: rphf|half|blwf
 RaRakaar [i: 280] - pos: prebase, masks: half|blwf
   Halant [i:  81] - pos:    base, masks: blwf

after BLWF:
     Reph [i: 181] - pos:    reph, masks: rphf|half|blwf
EyelashRa [i: 209] - pos: prebase, masks: half|blwf
       Ra [i:  52] - pos: prebase, masks: half|blwf
   Halant [i:  81] - pos:    base, masks: blwf
```

Here, because the prebase "Ra, Halant" and base "Ra" form a "RaRakaar", it now possesses the `half` and `blwf` masks. When the BLWF feature is applied, a multiple substitution separates the "RaRakaar" into an "EyelashRa, Ra".

![Screenshot from 2019-08-14 11-39-00](https://user-images.githubusercontent.com/8623831/62988559-2e1d1b80-be88-11e9-875b-2e71e564ef25.png)

### Prince

Noto Sans Devanagari "Ra, Halant, Ra, Halant, Ra, Halant":

```
before ligation:
       Ra [i:  52] - pos:    reph, masks: rphf
   Halant [i:  81] - pos:    reph, masks: rphf
       Ra [i:  52] - pos: prebase, masks: half|blwf
   Halant [i:  81] - pos: prebase, masks: half|blwf
       Ra [i:  52] - pos:    base, masks: none
   Halant [i:  81] - pos:    base, masks: none

after RPHF:
     Reph [i: 181] - pos:    reph, masks: rphf
       Ra [i:  52] - pos: prebase, masks: half|blwf
   Halant [i:  81] - pos: prebase, masks: half|blwf
       Ra [i:  52] - pos:    base, masks: none
   Halant [i:  81] - pos:    base, masks: none

after RKRF:
     Reph [i: 181] - pos:    reph, masks: rphf
 RaRakaar [i: 280] - pos:    base, masks: none
   Halant [i:  81] - pos:    base, masks: none

after BLWF: (no change)
```

No "EyelashRa, Ra" is formed, as the "RaRakaar" takes the properties of the base "Ra" (no masks).

![Screenshot from 2019-08-14 11-49-23](https://user-images.githubusercontent.com/8623831/62989040-daabcd00-be89-11e9-830d-43026f8b00ef.png)

**Comment by behdad** [comment]
You are correct that HB keeps mask from the "first" glyph in sequence when ligating.

In the case of the difference you point out, what does Uniscribe does.  Staying close to Uniscribe is basically what has driven what we do.  Unless we decide it does things different, I suggest you keep it similar to HB.

**Comment by adrianwong** [comment]
Thanks for confirming this, @behdad!

I don't believe that any of this is currently mentioned in the existing OpenType specification. If this is indeed _the_ approach to take with regards to ligation, then perhaps it may be worth elaborating on in some unofficial spec *** (even if only for posterity).

*** @n8willis would something like this be appropriate for this spec, or does it feel like it would be outside its scope?

**Comment by n8willis** [comment]
@adrianwong Because it can affect feature application, I would hesitantly say I think it's worth including here. Not sure where it best fits in, however ... which probably means 'errata'.
