### ISSUE TITLE
[Myanmar] Inappropriate example image for `pstf`

### ISSUE THREAD

**Issue by lianghai** [n8willis/opentype-shaping-documents#85]
The “ဝာ -> ဝါ” example at https://github.com/n8willis/opentype-shaping-documents/blob/master/opentype-shaping-myanmar.md#36-pstf is inappropriate, because the ာ–ါ variation/distinction is supposed to be implemented at the encoding level:

- U+102C ာ MYANMAR VOWEL SIGN AA
- vs., U+102B ါ MYANMAR VOWEL SIGN TALL AA

**Comment by lianghai** [comment]
I can’t really think of any reasonable use of `pstf` for Myanmar… The [example used in Microsoft’s spec](https://docs.microsoft.com/en-us/typography/script-development/myanmar#feature-tag-pstf) feels like a `psts` thing. Perhaps the variation of ု/ူ from being bottom-side to right-side? Fonts in the wild might have some innovative but conventional uses of `pstf` though.

**Comment by n8willis** [comment]
Yeah, when it was made Noto [didn't have anything](https://github.com/n8willis/opentype-shaping-documents/blob/master/images/myanmar/myanmar-image-generation-log.md#36-pstf) relevant, but at that point, Noto Sans was all there was. I'm looking at the Serif font now ... unfortunately it looks like it puts a LOT into `blwf` features that don't appear (to me) to be all that "below".

Ideally, IMO, if the feature is permitted by the spec, I would want to show it being used for something appropriate. Slightly less ideal would be to show it being used for something plausible and add a note that it's not commonly used in the wild; far less ideal is showing it used for something confusing or wrong. I mean, the point of these example images isn't to give type designers advice, it's to show shaper authors what functionality they're supposed to support.

**Comment by n8willis** [comment]
I do need to go back and regenerate images from Noto Serif Myanmar anyway, though. Since the Serif fonts tend to have more stroke contrast and less geometric body shapes, I leaned towards them for illustrations. @lianghai, if you get bored enough to poke at Noto Serif Myanmar (or some other open-source font we can build images with) and spot something that looks like a defensible option, I am all ears.

**Comment by lianghai** [comment]
For Myanmar, the mono-linear style is really the norm and very geometric design is also the norm. I don’t think it’s a good idea to use Noto Serif Myanmar for the Myanmar figures.

Myanmar really doesn’t have a use case for `pstf` (where right-side conjoining signs should be formed sequentially with a conjoiner and a base). As Indic OTL shapers have so many undocumented script-specific quirks, one can’t really assume how a feature is meant to be used and supported if the feature simply is not used in general fonts and supported by general shapers. It’s unwise to “show shaper authors what functionality they're supposed to support” according to theoretical analog of other scripts’ behavior. There simply isn’t any “functionality they're supposed to support”.

If you really want to avoid leaving this feature’s expected behavior undefined for Myanmar, just make it clear that it doesn’t have well attested usage, and point to some general, cross-script description of Indic shaping. Or just point to Devanagari.

**Comment by n8willis** [comment]
> For Myanmar, the mono-linear style is really the norm and very geometric design is also the norm. I don’t think it’s a good idea to use Noto Serif Myanmar for the Myanmar figures.

Good to know; thanks!

> Myanmar really doesn’t have a use case for `pstf` (where right-side conjoining signs should be formed sequentially with a conjoiner and a base). As Indic OTL shapers have so many undocumented script-specific quirks, one can’t really assume how a feature is meant to be used and supported if the feature simply is not used in general fonts and supported by general shapers. It’s unwise to “show shaper authors what functionality they're supposed to support” according to theoretical analog of other scripts’ behavior. There simply isn’t any “functionality they're supposed to support”.

Okay; not having the feature be meaningful definitely overrides concerns over illustration. 

> If you really want to avoid leaving this feature’s expected behavior undefined for Myanmar, just make it clear that it doesn’t have well attested usage, and point to some general, cross-script description of Indic shaping. Or just point to Devanagari.

That sounds reasonable.

**Comment by n8willis** [comment]
Should be fixed by edbc34c. 

I do also notice that, in the tag registry, it's one of those (many?) that doesn't explicitly [say](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-pstf) which scripts it's defined for. Since there are several of those, it might be worth adding to the errata.

**Comment by lianghai** [comment]
I’m imagining that somewhere (probably as a part of the OTL script tag registry) there should be definitions of script classes (say, CJK, Indic, RTL…) for the tag registry to refer to.

**Comment by n8willis** [comment]
> I’m imagining that somewhere (probably as a part of the OTL script tag registry) there should be definitions of script classes (say, CJK, Indic, RTL…) for the tag registry to refer to.

It looks like Norbert Lindenberg has spotted some similar (or, related) concerns, via [MS typography-issues 362](https://github.com/MicrosoftDocs/typography-issues/issues/362). Happy to keep an eye on that, but I suggest we take the topic to #57 from here.

**Comment by NorbertLindenberg** [comment]
More closely related: [MS typography-issues 290](https://github.com/MicrosoftDocs/typography-issues/issues/290).
