### ISSUE TITLE
HTML Comment showing with Mongolian document

### ISSUE THREAD

**Issue by alfiedotwtf** [n8willis/opentype-shaping-documents#91]
Not sure what's going on as the document itself looks fine, and so does running it through `markdown` locally. What I'm getting in the GitHub viewer is:

```
The cswh feature substitutes contextual swash variants of glyphs. <!---For example, the active font might substitute a longer variant of "Noon" when a certain number of subsequent glyphs do not descend below the baseline.--->
```

**Comment by n8willis** [comment]
I think it's just another example of Markdown begin Red Kryptonite. Anyway, closed now; putting things on separate lines is usually all it takes to get Markdown to unconfuse itself....
