### ISSUE TITLE
GDEF requirement

### ISSUE THREAD

**Issue by lianghai** [n8willis/opentype-shaping-documents#94]
Feeling stupid but I just noticed that HarfBuzz (and probably more shaping engines) requires the presence of the GDEF table (an empty is suffice) for executing the Indic reordering (of at least the Kannada script).

Is this information relevant and should be documented in this project?

See minimal test files: [DummyKnda.zip](https://github.com/n8willis/opentype-shaping-documents/files/4403437/DummyKnda.zip)

```
~ % hb-shape DummyKnda-Regular-without-GDEF.otf ರ್ಕ
[repha..Knda=0+0|ka..Knda=2+0]
~ % hb-shape DummyKnda-Regular-with-GDEF.otf ರ್ಕ 
[ka..Knda=0+0|repha..Knda=0+0]
```

**Comment by n8willis** [comment]
Hmm. Any idea why (or where) the lack of GDEF makes it fail?

As I recall, HarfBuzz usually works around bad GDEF content. E.g., the Indic2 state-machine stuff is all done by static Unicode data and a screwy GDEF won't cause HB to mis-shape things. So it should know what to do with a repha no matter what.

On the other hand, if it's causing a lower-level font-loading problem, and HB is just giving up before it even attempts shaping, that seems like it'd be out-of-scope — akin to having a malformed font binary.

**Comment by n8willis** [comment]
Is this the same issue as HB [2140](https://github.com/harfbuzz/harfbuzz/issues/2140)?

**Comment by lianghai** [comment]
Yes! Seems like the same problem!
